#version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
          #container_name: backend_container
    #command: ["poetry","run","uvicorn", "project.project.main:app", "--host", "0.0.0.0", "--port", "8000"]
    command: ["poetry", "run", "uvicorn", "project.main:app", "--host", "0.0.0.0", "--port", "8000"]

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
       - db
    # networks:
    #   - data_network
#--------------------------------------------------------------------------------------------------------------------------------
  frontend:
    build:
      context: .
      dockerfile: Dockerfilefront.dev
      #container_name: frontend_container
    command:  ["poetry", "run", "streamlit","run", "frontend/app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
    
    ports:
      - "8501:8501"
    volumes:
    #  - ./project/frontend:/app
     - .:/app
    depends_on:
      - backend
    # networks:
    #   - data_network
#---------------------------------------------------------------------------------------------------------------------------
  db:
    image: postgres:13
    container_name: db_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
#----------------------------------------------------------------------------------------------------------------------------
  broker:
    image: apache/kafka:3.7.0
    hostname: broker
    container_name: broker
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    # networks:
    #   - data_network
  #===============================================================================================================================
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - broker
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: 'local'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'broker:19092'
    # networks:
    #   - data_network
networks:
 default:
  driver: bridge 
volumes:
  postgres_data:

